twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        siteName: 'Médiathèque de La Chapelle-Curreaux'
        siteMail: 'testmail@test.com'
        sitePhone: '0000000000'
        categories: '@App\Repository\CategoryRepository'
        booksList: '@App\Repository\BookRepository'

when@test:
    twig:
        strict_variables: true
        
