twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        siteName: 'Médiathèque de La Chapelle-Curreaux'
        categories: '@App\Repository\CategoryRepository'

when@test:
    twig:
        strict_variables: true
        
